In [1]:
import numpy as np

In [2]:
arr= np.random.randint(1,10,(3,3))
arr1= np.random.randint(1,10,(3,3))
print(arr)
print(arr1)


[[3 6 5]
 [3 2 4]
 [7 4 8]]
[[3 6 5]
 [7 6 2]
 [3 1 3]]


In [3]:
#Addition
print(arr+arr1)

[[ 6 12 10]
 [10  8  6]
 [10  5 11]]


In [5]:
#Sub
print(arr)
print(arr1)
print(arr-arr1)

[[3 6 5]
 [3 2 4]
 [7 4 8]]
[[3 6 5]
 [7 6 2]
 [3 1 3]]
[[ 0  0  0]
 [-4 -4  2]
 [ 4  3  5]]


In [6]:
print(arr)
print(arr1)
print(arr*arr1)
print("--"*10)
print(arr/arr1)
print("--"*10)
print(arr%arr1)
print("--"*10)
print(arr//arr1)
print("--"*10)

[[3 6 5]
 [3 2 4]
 [7 4 8]]
[[3 6 5]
 [7 6 2]
 [3 1 3]]
[[ 9 36 25]
 [21 12  8]
 [21  4 24]]
--------------------
[[1.         1.         1.        ]
 [0.42857143 0.33333333 2.        ]
 [2.33333333 4.         2.66666667]]
--------------------
[[0 0 0]
 [3 2 0]
 [1 0 2]]
--------------------
[[1 1 1]
 [0 0 2]
 [2 4 2]]
--------------------


In [7]:
print(arr)
print(arr1)
print(arr.dot(arr1))

[[3 6 5]
 [3 2 4]
 [7 4 8]]
[[3 6 5]
 [7 6 2]
 [3 1 3]]
[[66 59 42]
 [35 34 31]
 [73 74 67]]


In [10]:
#Accessing Array Element using index and Slicing
arr= np.arange(1,31).reshape(6,5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [11]:
print(arr[0 ,0])
print(arr[4 ,2])

1
23


In [12]:
print(arr[::2 ,:])

[[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [13]:
print(arr)
print("---"*10)
print(arr[:,::2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
------------------------------
[[ 1  3  5]
 [ 6  8 10]
 [11 13 15]
 [16 18 20]
 [21 23 25]
 [26 28 30]]


In [14]:
print(arr)
print("---"*10)
print(arr[::2,::2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
------------------------------
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]


In [15]:
print(arr)
print("---"*10)
print(arr[:,(2,4)])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
------------------------------
[[ 3  5]
 [ 8 10]
 [13 15]
 [18 20]
 [23 25]
 [28 30]]


In [16]:
print(arr)
print("---"*10)
print(arr[:,(1,4)])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
------------------------------
[[ 2  5]
 [ 7 10]
 [12 15]
 [17 20]
 [22 25]
 [27 30]]


In [21]:
print(arr)
print("---"*10)
print(arr[(0,5),:])
print(arr[:,(0,4)])
print(arr[(0,5),0:5:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
------------------------------
[[ 1  2  3  4  5]
 [26 27 28 29 30]]
[[ 1  5]
 [ 6 10]
 [11 15]
 [16 20]
 [21 25]
 [26 30]]
[[ 1  5]
 [26 30]]


In [43]:
arr=np.random.randint(1,10,10)
print(arr)
print("---"*10)
arr.sort() #sort array colwise
print(arr)

[4 5 3 4 9 1 2 6 9 2]
------------------------------
[1 2 2 3 4 4 5 6 9 9]


In [27]:
arr=np.random.randint(1,10,(3,3))
print(arr)
print("---"*10)
arr.sort(axis=1) #sort array colwise
print(arr)


[[5 3 1]
 [4 1 7]
 [4 2 6]]
------------------------------
[[1 3 5]
 [1 4 7]
 [2 4 6]]


In [26]:
arr=np.random.randint(1,10,(3,3))
print(arr)
print("---"*10)
arr1=np.sort(arr,axis=0) #sort array Rowwise
print(arr1)

[[1 3 9]
 [3 7 2]
 [6 6 6]]
------------------------------
[[1 3 2]
 [3 6 6]
 [6 7 9]]


In [30]:
#append
arr=np.random.randint(1,10,(3,3))
arr1=np.random.randint(1,10,(3,3))
print(arr)
print("---"*10)
print(arr1)
print("---"*10)

arr3 = np.append(arr,arr1) #convert into 1d and append all elements
print(arr3)
arr3 = np.append(arr,arr1,axis=0) #appending data row wise
print(arr3)
print("---"*10)
arr3 = np.append(arr,arr1,axis=1) #appending data Column wise
print(arr3)
print("---"*10)

[[5 3 3]
 [8 1 3]
 [8 2 9]]
------------------------------
[[5 8 1]
 [2 9 8]
 [8 8 3]]
------------------------------
[5 3 3 8 1 3 8 2 9 5 8 1 2 9 8 8 8 3]
[[5 3 3]
 [8 1 3]
 [8 2 9]
 [5 8 1]
 [2 9 8]
 [8 8 3]]
------------------------------
[[5 3 3 5 8 1]
 [8 1 3 2 9 8]
 [8 2 9 8 8 3]]
------------------------------


In [31]:
#Filter Data
arr=np.random.randint(1,10,(3,3))
print(arr)
print("---"*10)
arr1=arr[arr%2==0]
print(arr1)

[[8 2 7]
 [4 9 4]
 [6 8 2]]
------------------------------
[8 2 4 4 6 8 2]


In [32]:
#Filter Data
arr=np.random.randint(1,10,(3,3))
print(arr)
print("---"*10)
arr1=arr[arr%2==1]
print(arr1)

[[7 7 5]
 [7 4 2]
 [8 8 7]]
------------------------------
[7 7 5 7 7]


In [34]:
#Filter Data
arr=np.random.randint(1,10,(3,3))
print(arr)
print("---"*10)
arr[arr%2==1]=-1
print(arr)

[[4 7 4]
 [9 3 4]
 [1 4 9]]
------------------------------
[[ 4 -1  4]
 [-1 -1  4]
 [-1  4 -1]]


In [40]:
arr=np.random.randint(1,10,10)
print(arr)
print("---"*10)
print(arr.argmin())#return 1st index of min value 
print(arr.argmax()) #return 1st index of max value 

[7 9 9 5 3 9 6 8 1 3]
------------------------------
8
1


In [41]:
#Unique values
arr=np.random.randint(1,10,10)
print(arr)
print("---"*10)
print(np.unique(arr))

[3 6 8 8 8 1 1 2 6 6]
------------------------------
[1 2 3 6 8]


In [44]:
#Iterate Through Array element
arr=np.random.randint(1,10,10)
print(arr)
for i in arr:
    print(i)

[8 7 3 4 9 6 8 3 1 8]
8
7
3
4
9
6
8
3
1
8


In [45]:
#reverse
arr=np.random.randint(1,10,10)
print(arr)
print(arr[::-1])

[5 4 9 8 7 9 7 8 4 5]
[5 4 8 7 9 7 8 9 4 5]
